language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run coverage
deploy:
  provider: elasticbeanstalk
  access_key_id: "$ACCESSKEYID"
  secret_access_key: "$ACCESSKEYSECRET"
  region: us-east-2
  app: Tutorials
  env: Tutorials-env
  bucket_name: travis-deployment-resevoir
  on:
    branch: master
after_success: npm run coveralls
env:
  global:
  - secure: ccav6OQCBkqc8SJ0M7zfA40QbqaVFvJCt5VgsUd8pC7ZCaTSV1oxilSjXv0rmV8l4S2qXj4Kug1kdqPP0Zn60ipE9+gJ9FRX4WQs4JXPgCBxNAJYUnus4rNVvGYTJNZyfHry9XJPZS8SJ9g19WnL+7JwXxKwsCkkpEnM/h6LB7fjYoVetUh0zSfzpK8VoCZr42c43JJAO3mXhOIPuM8nfFR4s5DNVx8G0z+VufbhKnCzwtVtNhUQvZGs3bj+0HgO05CxOX1D6tHeDarrTYDf3o1C+cZMBe/vt9/boUCCEm1vRAUCWt4pAxYGD5t9Hnhn1dsNNVvhOndrQy34q2NFjo9S+y7XiQM648ploxwx5jlHQWuk0KJoPtOR/+pJfA5J6c62tPigfZ0WAolXyzzvEToM+mSui9zkfUwrQNLIgEvltijiV0rcGo2hXEh/1oz6CBrM1+t7IowYPIhQIZ61erQ9C8B/CRaXQz5d7+SrwnlFPbxmAoUq7ON46DwGCnkJTfqR2IC+qnVGIKzysY0MwsVZS2/ncvAy+fVh70x+l18Iyy4dS9W8VbRJC91D0/I5nx7NywzJFnmYOOMXtBKrUtAl+Urym5Ul4cu2RBsDB1pFwF5d/9Ejn970c539HnwMQtciggkZ7WfIATlUxGWLoVoxgmOJB83YaPS/i6CaDZo=
  - secure: tUbTOGNbuvgRpgdcJMc8tzVOcB0/oqGzAEbeXwh5JDQ3IEutwNn3AEWLRfJ/rw4JC0/mXAuIwRX5hcY+GZqPtKmzui4LMv964kRso73mWigkN0+nZDydpYnrqGw1Y4kZ8W9RDrz3EFSoI4kdjW1BH8Oa0yO+lSXjBBIhTWSHzRka/emY8dUmn4tSyJzZXAN4vncnVYlbpIyds0vE87H2F1i4rTFnAwdMg6PF+8af0qazRaKO+m6YfC1HVNQXzHD+qrs49SPNMJ0b1HarNdOjnIL4i+ktLOICOz2TZeUZpq4M8EoDQffjWPvVLV8AgLD1grb+dLlGMFwURwFqKegPXtsw79vO4Dr5v+MSmC86HpX1tNfO0H8CHUOg+xm1lyOiJGJPrup/l1BnP8xHT2EYCZjq9T3MKN3wuKqTD4bx/t1Gm6gYFR1CVjGpgo2WM7+XcgbvsyGarO+bqzNupLUFPYrXwh1SclEvAuHokUeXGTcccCy2X2563A7xidBYomgZ2ap9uMsCXoeQNnqO8Kq4mgY2S76DE/7NoLpQuEbTaeugocWz7qK7fdENeWQhiE3dEuSBEY+VzZIHjVT6m/foTnqOqAKFP0Duzqdu8m/pAoQC9DXqbD0hK9X3D047iPt5yqrNYMh7Vdj0L+/w52nAZ1Fqr9doi+JzHNEPMs/sg7E=
