language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run coverage
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: nXBCcHOGc5WhU8kwPzkWCctbchhZHbVxrRBQJPQC/cI+Tuu5ayNSwO85dfboFserNb7CBVl9oknHAaR35BG+fmatxdzRHPdRVnRwu6zNRi2EHEqivjYHsS9vqQAHMeJK/vcV9lQ3krCcFzNBYeOAG4sdxPS+84MDwZLqgGOaJmq8Iw3ydgXO921+eNSEXQWLo2cLrk7fDIXmsT3KZcXX5q9ihf1lp2jPmMVNA9P6VOv85/ywBglpmqyMixAqs3YwmsAJbqIaLIJQcspc0EvNyHA2zwJe/iFwGs+O0BQgm3Rf9iUFk+emox+ZDu6sReF577KRtnfaf8YhZNPg0NddvoBUi8vDZ03SC8vDAyKYLODCuvrkS6WuXaJrYak+xjkit/2K4+uMTS6hLeLuSTO2LHZjBjz6YJsGngrTDda1AHahSSGTPB49t4SuxlujY5RVmrK0Id5A5EgMyBbNnce88LtpR2uVutR09AgUMhl3a9fKd1jYG9V+7ScfBnEbRXniFL4uMhVsdsTD/pdqCoZuPvFf9SNj0bfNC8cLwbG30a3of1p6fQUqtYyFFGCEpKl0jYz1gduRoKJOuSBrIuG7j0/sao5i3IWsevBx/Jd32AHHyG+YJzldQQn8RkZDBGsmhvHfwfTRoDYBc8ffdd7ORtvV3/uKntBYFhpZmZ5vqmw=
  secret_access_key:
    secure: WNuxBnx8o0zwGsfP+jjfNZjQAdmVp1yiOH1xQrERu4oOiYCzkRyajePfk4DeEvxTjJiY3UycVoH6sWap1+nq69dXkkMGr5tNJIjsc1e/I6Imk7mYGz94YQIkjfqeWXjSy46qP3eCcUQyK9kh59rv/fO4rrEJPj19UQSYB2JGdrZ/lJJ6zIBaNt1qX9UYrM2O7vshsP6JvAvs0vpOJ28sdgLk8hu8UQDyxPi88evqh3o/ATHht1S2bQ8XrTGDQ88FlOPyYZBrl2IOQg6HEGp+1iDCxkOkxTk9FHqPWEfjYcrwllCw10Zfk9N2E/vO6gIoiSLZipQA68N/GbZz10xzPljWxaevBiaUn2aWz7z8xmTVsbu/6T623WdG8vwydCZx3iR6kS/S6Ma3XoWnzQjSIlK7YjQ3CNW4bb1KooBFYigmnvLOKgXCa92Lj4DreaTqnk61RklZMYPlGCec9jod30/5hon9ccGx4EFFbT1F3wDnaigoJ+d3eKOBNc7qlVecfEtp2HLv9MAMba4/HVSzKuZZB/bPnoKHDJA7F6oSoxxnoQMn3hE9QLb4nFmqc1csWITqmCLK1lWSwTlD/pY0O5TYPBrSl0C3KCc5gWUa5xNOkoarBex/nRkX+ch2sKxouZEuPoyQQIeskHlTeGF190llnQtuGfK4Z6QczBiR/8E=
  region: us-east-2
  app: Tutorials
  env: Tutorials-env
  bucket_name: travis-deployment-resevoir
  on:
    branch: master