version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
    - "4569:4569"
    - "4576:4576"
    - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
    - SERVICES=dynamodb,sqs
    - DEBUG=${DEBUG- }
    - DATA_DIR=${PWD}/localstack/data
    - PORT_WEB_UI=${PORT_WEB_UI- }
    - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
    - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
    - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
    - "${PWD}/localstack:${PWD}/localstack"
    - "${PWD}/init.sh:/docker-entrypoint-initaws.d/init.sh"